<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ceml</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>ceml</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^\s*(assignment)\s+\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.assignment.ceml</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.unquoted.ceml</string>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>meta.assignment.ceml</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(assign)\s+(\w+)\s*\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.assignment.ceml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.roles.ceml</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.unquoted.ceml</string>
			<key>end</key>
			<string>}</string>
			<key>name</key>
			<string>meta.assign.ceml</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.offering.ceml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.ceml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.roles.ceml</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.ceml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(offering)\s+("[^"]+")\s+\(([\w\d, ]+);\s+(\d+m)\)</string>
			<key>name</key>
			<string>meta.offering.ceml</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.offering.ceml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.ceml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(discern)\s+(\w+)</string>
			<key>name</key>
			<string>meta.discern.ceml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(type|for|rank|lasting|takes|req|popularity|players|from|provides|in|join|cue|end|exit|join_cue|cue_act)\b</string>
			<key>name</key>
			<string>support.variable.ceml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(nearby_landmark|many)\b</string>
			<key>name</key>
			<string>support.constant.ceml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(context|ask)\b</string>
			<key>name</key>
			<string>keyword.control.ceml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(then)\b</string>
			<key>name</key>
			<string>keyword.operator.ceml</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.idea.ceml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.idea.ceml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(snippet|to|ask)\s+([.a-zA-Z0-9_/-]+)</string>
			<key>name</key>
			<string>meta.moo.ceml</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.js</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash.js</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+m?\b</string>
			<key>name</key>
			<string>constant.numeric.ceml</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.ceml</string>
				</dict>
			</dict>
			<key>match</key>
			<string>:\s+(.*)$</string>
			<key>name</key>
			<string>meta.assign-stanza.ceml</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.ceml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.ceml</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ceml</string>
	<key>uuid</key>
	<string>BE4CE07F-C4D9-40FE-82BB-2BB28B2DE828</string>
</dict>
</plist>
